In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x=[8.0, 1,2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]

print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [4]:
y, y_with_nan=np.array(x), np.array(x_with_nan)
z, z_with_nan=pd.Series(x), pd.Series(x_with_nan)

print(y)
print(y_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]


In [5]:
print(z)
print(z_with_nan)

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


# Mean

In [6]:
x

[8.0, 1, 2.5, 4, 28.0]

In [7]:
sum(x)/len(x)

8.7

In [8]:
mean_ = sum(x)/len(x)
mean_

8.7

In [9]:
mean_ = statistics.mean(x)
mean_

8.7

In [10]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

In [12]:
x_with_nan

[8.0, 1, 2.5, nan, 4, 28.0]

In [11]:
mean_ =np.mean(y)
mean_

8.7

In [13]:
mean_ = y.mean()
mean_

8.7

In [14]:
np.mean(y_with_nan)

nan

In [15]:
y_with_nan.mean()

nan

In [16]:
np.nanmean(y_with_nan)

8.7

In [17]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [18]:
z.mean()

8.7

In [19]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

In [20]:
z_with_nan.mean()

8.7

# Weighted Mean 

In [24]:
var=[2,2,4,4,4,4,4,8,8,8]
len(var)

10

In [25]:
(0.2 * 2) + (0.5 * 4) + (0.3 * 8)

4.8

In [30]:
x=[8.0, 1, 2.5, 4, 28.0]
w=[0.1, 0.2, 0.3, 0.25, 0.15]

In [31]:
sum(w)

1.0

In [32]:
wmean=sum(w[i] * x[i] for i in range(len(x))) / sum(w)
print(wmean)

6.95


In [33]:
wmean=sum(x_ * w_ for (x_,w_) in zip(x,w)) / sum(w)
print(wmean)

6.95


In [34]:
y,z,w= np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

6.95


In [35]:
np.average(z, weights=w)

6.95

In [36]:
(w*y).sum() / w.sum()

6.95

# Harmonic Mean 

In [37]:
hmean = len(x) / sum(1/ item for item in x)
hmean

2.7613412228796843

In [39]:
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

In [40]:
(60+20) / 2

40.0

In [42]:
(2+4+6+100) / 4

28.0

In [43]:
4 / (1/2 + 1/4 + 1/6 + 1/100)

4.316546762589928

In [45]:
statistics.harmonic_mean(x)

2.7613412228796843

In [46]:
np.mean(x)

8.7

In [47]:
x

[8.0, 1, 2.5, 4, 28.0]

In [48]:
scipy.stats.hmean(y)

2.7613412228796843

In [49]:
scipy.stats.hmean(z)

2.7613412228796843

# Geometric mean 

In [ ]:
2,18

In [50]:
2*18

36

In [53]:
gmean=1

for item in x:
    gmean*= item
    
gmean

2240.0

In [54]:
gmean **= 1/len(x)
gmean

4.677885674856041

In [55]:
scipy.stats.gmean(y)

4.67788567485604

In [57]:
scipy.stats.gmean(z)

4.67788567485604

# Median 

In [63]:
n = len(x)

if n%2:
    median_ = sorted(x)[round(0.5 * (n-1))]
else:
    x_ord, index = sorted(x), round(0.5*n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])
    

median_

4

In [59]:
n%2

5

In [61]:
statistics.median_low(x[:-1])

2.5

In [62]:
statistics.median_high(x[:-1])

4

In [65]:
statistics.median(x_with_nan)

6.0

In [66]:
statistics.median_high(x_with_nan)

8.0

In [67]:
statistics.median_low(x_with_nan)

4

In [68]:
np.median(y)

4.0

In [69]:
np.median(y[:-1])

3.25

# Mode 

In [70]:
u = [2,3,2,8,12]
v=[12,15,12,15,21,15,12]

mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [71]:
statistics.mode(u)

2

In [72]:
u,v = np.array(u), np.array(v)

mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [73]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [75]:
print(mode_.mode)
print(mode_.count)

[12]
[3]


In [78]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

In [79]:
u.mode()

0    2
dtype: int32

In [81]:
v.mode()

0    12
1    15
dtype: int32

In [82]:
w.mode()

0    2.0
dtype: float64

# Measures of Variability 

In [84]:
n = len(x)

mean_ = sum(x) / n
mean_

8.7

In [85]:
sum((item - mean_)**2 for item in x) / (n-1)

123.19999999999999

In [86]:
statistics.variance(x)

123.2

In [87]:
np.var(y, ddof=1)

123.19999999999999

In [88]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [89]:
z.var(ddof=1)

123.19999999999999

In [ ]:
1,2,3,4,5,6,7,8,9,10

# Standard Deviation 

In [100]:
std_ = var_ ** 0.5
std_

11.099549540409285

In [101]:
var_ ** 0.5

11.099549540409285

In [93]:
statistics.stdev(x)

11.099549540409287

In [94]:
np.std(y, ddof=1)

11.099549540409285

In [95]:
z. std(ddof=1)

11.099549540409285

# Skewness 

In [96]:
x

[8.0, 1, 2.5, 4, 28.0]

In [103]:
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std = var_** 0.5

skew_ = (sum((item-mean_)**3 for item in x) * n / ((n-1)*(n-2)* std_**3))
skew_

1.9470432273905929

In [104]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [105]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [106]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
z.skew()

1.9470432273905924

In [107]:
z_with_nan.skew()

1.9470432273905924

# Percentiles 

In [108]:
x = [-5.0, -1., 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]
statistics.quantiles(x, n=2)

[8.0]

In [109]:
statistics.quantiles(x, n=4, method='inclusive')

[0.1, 8.0, 21.0]

In [110]:
y = np.array(x)
np.percentile(y, 5)

-3.4

In [111]:
np.percentile(y, 95)

34.919999999999995

In [112]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [113]:
np.median(y)

8.0

In [115]:
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan

array([-5. , -1. ,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [116]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

# Ranges 

In [117]:
np.ptp(y)

46.0

In [118]:
np.ptp(z)

27.0

In [119]:
sorted(y)

[-5.0, -1.0, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [120]:
41 - (-5)

46

In [121]:
np.amax(y)

41.0

In [122]:
np.amin(y)

-5.0

In [123]:
np.amax(y) - np.amin(y)

46.0

# Summary of Desc Stat

In [124]:
result = scipy.stats.describe(y, ddof=1, bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.633333333333333, variance=228.435, skewness=0.9262368392503544, kurtosis=0.1520857728577445)

In [125]:
result.nobs

9

In [126]:
result.minmax[1]

41.0

In [127]:
result.skewness

0.9262368392503544

In [134]:
result = z.describe()
result

count     5.00000
mean      8.70000
std      11.09955
min       1.00000
25%       2.50000
50%       4.00000
75%       8.00000
max      28.00000
dtype: float64

In [135]:
result['25%']

2.5

In [136]:
result['mean']

8.7

# Correlation

In [132]:
x = list(range(-10, 11))
y = [0,2,2,2,2,3,3,6,7,4,7,6,6,9,4,5,5,10,11,12,14]

In [133]:
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x), pd.Series(y)

In [140]:
n = len(x)
mean_x, mean_y = sum(x) / n, sum(y) / n

cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n))
         / (n-1))
cov_xy

19.95

In [141]:
np.cov(x_, y_)

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [142]:
x_.var(ddof=1)

38.5

In [143]:
y_.var(ddof=1)

13.914285714285711

In [144]:
np.cov(x_, y_)[0,1]

19.950000000000003

In [145]:
np.cov(x_, y_)[1,0]

19.950000000000003

# Correlation Coefficient 

In [147]:
var_x = sum((item - mean_x)**2 for item in x) / (n-1)
var_y = sum((item - mean_y)**2 for item in y) / (n-1)

std_x, std_y = var_x ** 0.5, var_y ** 0.5

r = cov_xy / (std_x * std_y)

In [148]:
r

0.861950005631606

In [149]:
scipy.stats.pearsonr(x_, y_)

(0.8619500056316058, 5.122760847201207e-07)

In [150]:
np.corrcoef(x_, y_)

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [151]:
np.corrcoef(x_, y_)[0,1]

0.8619500056316061

In [153]:
scipy.stats.linregress(x_, y_)

LinregressResult(slope=0.5181818181818182, intercept=5.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [154]:
scipy.stats.linregress(x_, y_).rvalue

0.861950005631606

y = mx + c

In [155]:
x__.corr(y__)

0.8619500056316061

In [156]:
y__.corr(x__)

0.8619500056316061

In [157]:
a = np.array([[1,1,1],
             [2,3,1],
             [4,9,2],
             [8,27,4],
             [16,1,1]])
a

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [158]:
np.mean(a)

5.4

In [160]:
a.mean()

5.4

In [161]:
np.median(a)

2.0

In [162]:
a.var(ddof=1)

53.40000000000001

In [163]:
np.mean(a, axis = 0)

array([6.2, 8.2, 1.8])

In [164]:
a.mean(axis=0)

array([6.2, 8.2, 1.8])

In [165]:
np.mean(a, axis = 1)

array([ 1.,  2.,  5., 13.,  6.])

In [166]:
a.mean(axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [167]:
np.median(a, axis=0)

array([4., 3., 1.])

In [168]:
np.median(a, axis=1)

array([1., 2., 4., 8., 1.])

In [169]:
a.var(axis=0, ddof=1)

array([ 37.2, 121.2,   1.7])

In [170]:
a.var(axis=1, ddof=1)

array([  0.,   1.,  13., 151.,  75.])

In [171]:
scipy.stats.gmean(a)

array([4.        , 3.73719282, 1.51571657])

In [172]:
scipy.stats.gmean(a, axis=1)

array([1.        , 1.81712059, 4.16016765, 9.52440631, 2.5198421 ])

In [173]:
scipy.stats.gmean(a, axis=None)

2.829705017016332

In [174]:
scipy.stats.describe(a, axis=None, ddof=1, bias=False)

DescribeResult(nobs=15, minmax=(1, 27), mean=5.4, variance=53.40000000000001, skewness=2.264965290423389, kurtosis=5.212690982795767)

# Dataframe 

In [175]:
row_names = ['first', 'second', 'third', 'fourth', 'fifth']
col_names = ['A', 'B', 'C']

df=pd.DataFrame(a, index=row_names, columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [176]:
df.mean()

A    6.2
B    8.2
C    1.8
dtype: float64

In [177]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [178]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64

In [179]:
df["A"]

first      1
second     2
third      4
fourth     8
fifth     16
Name: A, dtype: int32

In [180]:
df["A"].mean()

6.2

In [181]:
df["A"].var()

37.20000000000001

In [183]:
df.values

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [184]:
df.to_numpy()

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [185]:
df.describe()

A          B        C
count   5.00000   5.000000  5.00000
mean    6.20000   8.200000  1.80000
std     6.09918  11.009087  1.30384
min     1.00000   1.000000  1.00000
25%     2.00000   1.000000  1.00000
50%     4.00000   3.000000  1.00000
75%     8.00000   9.000000  2.00000
max    16.00000  27.000000  4.00000